### PR TITLE
Add progress bar callback function #7

### PR DESCRIPTION
**Pull request by FlorianK13**

### CODE REVIEW

**Comment by FlorianK13** [comment]
@khdlr I did not come up with a test for that, maybe we merge it now and test it as soon as we integrate it in our frontend?

**Comment by FlorianK13** [comment]
@khdlr can you add your review so that I can merge?

**Review by khdlr — CHANGES_REQUESTED** [review]
Missing `/ 3` when calling the progress callback

**Comment by khdlr** [comment]
Sorry, didn't realise it's a two step process where I have to first "start a review" and then "finalize the review" :sweat_smile:

**Review by khdlr — CHANGES_REQUESTED** [review]
We need it for `i` as well :)

**Comment by FlorianK13** [comment]
> We need it for `i` as well :)

Ups...

**Review by khdlr — APPROVED** [review]

**Pull request merged**
